### ISSUE TITLE
Instalación de Django

### ISSUE THREAD

**Issue by jtmeyer98** [IIC3103/2022-1-dudas#1]
Hola! Estoy siguiendo la guía de instalación recomendada en clases:
https://devcenter.heroku.com/articles/getting-started-with-python#run-the-app-locally

Y al correr --> python manage.py collectstatic
se muestra el siguiente error, el cual no he podido resolver buscando soluciones en internet.

<img width="758" alt="image" src="https://user-images.githubusercontent.com/37156969/160009139-42e6a0ba-e662-4331-9eef-126a6497a659.png">

Estoy usando WSL2 en un S.O. windows.

Debo estar dentro o fuera del venv?

**Comment by Deleon20** [comment]
Hola! 

Una de las gracias de usar Django es que esta disponible para windows ya que usa Python, por lo que te recomiendo usarlo fuera de WSL2.

Ahora al momento de desarrollar tu aplicación lo hiciste tambien en WSL2?

**Comment by jtmeyer98** [comment]
Todo lo he realizado en WSL2, el profesor y el ayudante me recomendaron que era mucho mejor. La actividad 2 la realicé con WSL2 también. 

Pero tu me dices que es mejor utilizar el PowerShell de Windows? y ahí realizar toda la instalación? (desde heroku hasta Django)

Siguiendo este link: 
https://devcenter.heroku.com/articles/getting-started-with-python#set-up

**Comment by Deleon20** [comment]
Si estabas usando exclusivamente WSL2 no hay problema.

Ahora en torno a tu error al parecer no se instalo correctamente Django.

¿Cuando corriste `pip install -r requirements.txt` te aparecio algun error? Y tienes instalado Postgres?

**Comment by jtmeyer98** [comment]
Lo pude solucionar al instalar postgres, Gracias!!
