### ISSUE TITLE
Problema con endpoint GET /oauth/grant

### ISSUE THREAD

**Issue by dasolari** [IIC3103/2022-1-dudas#10]
Hola! Llevo varios días intentando solucionar un problema que me arroja la prueba Nº 5 de la planilla. El problema es que no me aparece un mensaje descriptivo, solo dice `'NoneType' object has no attribute 'token'`. He intentado solucionarlo y lo he probado, tanto localmente como en producción y no logro entender la razón del error, todos los casos borde retornan un objeto. 

Además revisé los logs de Heroku al momento en que se hacen las requests y la aplicación no arroja ningún error. ¿Existe la posibilidad de que puedan hacer que la plantilla arroje un error más descriptivo para esta prueba?

**Comment by dedarritchon** [comment]
Hola @dasolari, lo revisamos!

**Comment by dedarritchon** [comment]
Se corrigieron los logs
