### ISSUE TITLE
Consulta ID

### ISSUE THREAD

**Issue by rsnegrin** [IIC3103/2022-1-dudas#11]
Hola!
Una pregunta, en las tablas del anexo del enunciado dice que los ID de los usuarios son varchar, pero en la página de la documentación de la API los muestra como int. Existe alguna reestricción para esto? Porque estaba usando la libreria 'uuid' para hacer los IDs de los usuarios (no tienen un orden lógico núimerico) y estos son strings. 
Gracias!

**Comment by dedarritchon** [comment]
respondido en https://github.com/IIC3103/2022-1-dudas/issues/7
