### ISSUE TITLE
Problema con el repo y heroku

### ISSUE THREAD

**Issue by jtmeyer98** [IIC3103/2022-1-dudas#12]
Clone el repo en mi escritorio, luego le añadí los archivos de otro repo "tipo" para comenzar a hacer la API con Django, y deployé la API con heroku. Pero después me arrepentí de usar esos archivos por lo complicados que eran y los eliminé para comenzar armando la API desde cero. El problema que tengo es el siguiente:

Comencé por crear otra app en heroku y al hacer 'git push heroku main' pasa lo siguiente:

<img width="730" alt="image" src="https://user-images.githubusercontent.com/37156969/160737193-4a352585-2468-4c10-89ec-869e0eb9109f.png">

Luego hice lo siguiente:

<img width="717" alt="image" src="https://user-images.githubusercontent.com/37156969/160737257-18c3e1a8-39d7-4717-b2ed-193c14ffafaa.png">

Las soluciones que encontré en internet son:

1) usar otra rama de GIT (no me funcionó)
2) crear un nuevo repositorio

Creo que no es bueno crear otro repositorio porque la manera de corrección que están usando es con los repos que nos dieron.

¿Hay una posibilidad de que me den un repo nuevo para comenzar con la tarea de buena manera? sin arrastrar estos problemas que tengo

Si no es posible, ¿Qué puedo hacer? la verdad estoy muy angustiado porque la tarea se entrega en poco tiempo y no llevo nada.

**Comment by Deleon20** [comment]
Hola! 

El error te esta diciendo que basicamente heroku no sabe que lenguaje estas usando. Heroku cuando haces un push busca en los archivos si es que hay algun archivo correspondiente a un lenguaje especifico, por ejemplo si encuentra `package.json` seria un proyecto nodejs. Para que detecte Django tienes que incluir un archivo llamado `requirements.txt `, tienes ese archivo en tu repositorio?

**Comment by jtmeyer98** [comment]
Ahora agregué el archivo requirements.txt, que incluye:

django
gunicorn
django-heroku
requests

y ya no me muestra el error anterior. Pero me muestra el siguiente:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/37156969/160924717-be7b6525-e403-40ad-a2a6-4396610a4d3d.png">

Al parecer esta buscando un proyecto anterior de heroku, que yo había eliminado desde la página de heroku.

**Comment by jtmeyer98** [comment]
Te molestaría mucho si hacemos un zoom y resolvemos esto más rápido?

Si es que es posible

**Comment by jtmeyer98** [comment]
Ya dale!! te aviso como me va

**Comment by jtmeyer98** [comment]
Tengo este problema ahora

<img width="692" alt="image" src="https://user-images.githubusercontent.com/37156969/160945244-1617ab87-d4bb-42f1-884f-b6ab2825021a.png">

he buscado y he tratado varias cosas pero no se como solucionarlo

**Comment by dedarritchon** [comment]
Hola @jtmeyer98! Puedes mostrar lo que estás subiendo a Heroku? (los archivos y carpetas que estés subiendo). Heroku espera que tu app venga con cierta estructura por lo que puede ser que la esté rechazando porque no sigue con la estructura esperada. En particular es importante que en la carpeta raíz de lo que estés subiendo venga el archivo requirements.txt y el Procfile, si esos archivos no están, o no tienen exactamente ese nombre, Heroku no lo va a reconocer. también Los comandos que corras en el Procfile deben ir referenciados desde el root, por ejemplo si el comando para levantar tu app es **python main.py**, ese archivo **main.py** tendría que estar en el root junto al Procfile, saludos!

**Comment by jtmeyer98** [comment]
Hola, arreglé lo de la estructura agregando el requirements.txt y el Procfile

<img width="545" alt="image" src="https://user-images.githubusercontent.com/37156969/161081710-160da78a-cba6-4342-ac9e-2d3f81254cc6.png">

El problema que tengo ahora al correr git push heroku main es el siguiente:

<img width="725" alt="image" src="https://user-images.githubusercontent.com/37156969/161081410-e3089224-84d5-471c-aa15-125f5da0ffed.png">

**Comment by Deleon20** [comment]
Hola! Si te das cuenta mas arriba del pantallazo te tiro errores de Procfile y que faltaban modulos, seguramente no las pusiste en requirements.txt!

**Comment by dedarritchon** [comment]
Sii, el primer error indica que falta la librería **djangorestframework** en tu requirements.txt,y para arreglar el segundo error prueba corriendo ese comando sugerido: **heroku config:set DISABLE_COLLECTSTATIC=1**
