### ISSUE TITLE
Problemas en Crear Usuarios plantilla ( {"bad_request": "OK", "ok": []})

### ISSUE THREAD

**Issue by bpeirano1** [IIC3103/2022-1-dudas#13]
Hola,
En la plantilla de corrección de la Tarea 1 me aparece solo este error:
{"bad_request": "OK", "ok": []}

y no me da más información al respecto. Tampoco me aparece nada en los logs de heroku.

Así que agradecería si me pueden indicar a qué se refiere ese error.

Gracias de antemano,

**Comment by dedarritchon** [comment]
Hola! listo, se corrigió el log, saludos!
