### ISSUE TITLE
Formulario de entrega de tarea según Tarea en Canvas

### ISSUE THREAD

**Issue by juanfcolopez** [IIC3103/2022-1-dudas#15]
Hola, una consulta, para entregar la tarea se menciona que se debe dejar la URL de la app y el del repo en un formulario que iba a estar disponible en el sitio del curso y además dejarlas en el excel donde están los test. Mi duda es, dónde está el formulario de canvas para dejar los urls? o basta con solo dejarlos en el excel de los test?

**Comment by Deleon20** [comment]
Hola! Dejarlo en la planilla es mas que suficiente!
