### ISSUE TITLE
Tester no reconoce body enviado, pero postman si

### ISSUE THREAD

**Issue by totichi** [IIC3103/2022-1-dudas#16]
Hola!
Tengo un problema en que el tester no reconoce el body que la api envía como respuesta, pero si hago el mismo request por postman hacia la api en heroku si se ve el body. El código de respuesta está bien, lo único diferente en el tester es que el body aparece como "null", mientras que en postman aparece el body con la respuesta correcta.
- El content-type si está asignado a application\json
Un ejemplo del problema que tengo en el tester es el siguiente:
```
{"status": "FAILED", "detail": {"method": "POST", "endpoint": "https://tarea1-tallerintegracion.herokuapp.com/users", "request_body": {"username": "Jayperez", "name": "Jos\u00e9 Perez", "password": "kldjkqwihjd", "psu_score": 612, "age": 30, "university": "Valdivia High", "gpa_score": 90.12, "job": "Operador de maquinaria pesada", "salary": 2389237.94, "promotion": true, "hospital": "Hospital San Juan de Dios", "operations": ["Fractura de f\u00e9mur", "Extracci\u00f3n de muela"], "medical_debt": 323767.6}, "request_headers": null, "expected_status": 400, "expected_body": {"error": "your error message"}, "status_received": 400, "body_received": null, "exception": "incorrect response"}}
```
Pero si hago el mismo request (por segunda vez)por postman obtengo lo siguiente:
![image](https://user-images.githubusercontent.com/37162517/160943141-2e0e3855-a2e0-4a72-ac28-87c2ca4c18b1.png)
![image](https://user-images.githubusercontent.com/37162517/160943234-aa31186f-1c6c-4c34-9136-0a909e46e066.png)

Gracias de antemano!

**Comment by dedarritchon** [comment]
Hola @totichi! Había un problema con el log, el status en esa parte del test (conflict), es 409.

![image](https://user-images.githubusercontent.com/17625557/160960593-5767c6a0-1ed2-4442-8002-e0d36dbc98ea.png)

El test lo único que hace es tratar de crear nuevamente los usuarios que se crearon inmediatamente antes.
Ya fue corregido el log,
Saludos!

**Comment by dedarritchon** [comment]
@totichi sobre la segunda imagen, esa config es del lado de PostMan al hacer el request a tu app. El formato que retorne tu app depende de los headers que incluyas al armar el response, pero la implementación de eso depende del lenguaje y framework que estés usando.
