### ISSUE TITLE
Atributos opcionales para creación de usuario

### ISSUE THREAD

**Issue by daleal** [IIC3103/2022-1-dudas#18]
Hola! Me surgió la duda de qué atributos son opcionales para la creación de usuario y cuales no. En uno de los tests se crea un usuario sin el atributo `promotion` y se espera que se cree correctamente, pero no encuentro ningún lugar (ni el enunciado, ni la referencia de la API, ni un anuncio) que diga que dicho atributo es opcional, ni qué valor debería recibir por _default_. ¿Qué atributos debería dejar opcionales durante la creación de un usuario y qué valor debería tener por _default_ cada uno?

**Comment by daleal** [comment]
Muchas gracias!

**Comment by dedarritchon** [comment]
Hola @daleal! Si, disculpa si faltó detallar un poco más eso, en el enunciado se menciona en el apartado **Crear Usuario**:

![image](https://user-images.githubusercontent.com/17625557/160958212-fd7736d6-ce56-4dd9-bd7d-244347ae31f3.png)

Los campos sin valor pueden quedar nulos.
Saludos!
