### ISSUE TITLE
Solicitud de más plazo para T1

### ISSUE THREAD

**Issue by juansegmart** [IIC3103/2022-1-dudas#19]
Estimado profesor y ayudantes. El motivo de esta issue es para solicitar la extensión del plazo de entrega de la tarea para este fin de semana, ya que me he comunicado a través del grupo de Telegram del curso y un alto número de estudiantes al igual que yo se han visto complicados para poder avanzar con la tarea a tiempo, por el hecho de que varios cursos del DCC tenían entregas esta semana.
Agradeceríamos que por favor puedan considerar esta petición de forma excepcional.

**Comment by sbersanii** [comment]
Por ser la primera tarea siento que gaste mucho tiempo en instalar todo lo necesario, ya que en general aparecen bugs, problemas con las versiones, etc. sería bueno tener algo más de plazo.

**Comment by itplanella** [comment]
Sii agradeceríamos mucho que den más plazo para poder entregar una mejor tarea. El setup fue más complicado de lo esperado 😅

**Comment by jnvillarroel** [comment]
Por favoooor! Al igual que a mis compañeros el set up me tomó muuuchísimo tiempo, ojalá pudieran extender el plazo, considerando ademas que esto no implicar acortar el plazo de las próximas entregas!!

**Comment by bdiaz3** [comment]
Porfavor!! Al ser todo tan nuevo se ha gastó mucho tiempo en partir la tarea. Tiempo extra estaría increíble para poder entregar una tarea de calidad.

**Comment by dedarritchon** [comment]
Estimados, el profesor envió un anuncio por Canvas avisando que se dará más plazo para la tarea, lo dejo por acá también:

A raíz de las dificultades que han tenido varios de ustedes con la tarea 1, he decidido posponer la entrega para el lunes 4 de abril a las 18:00.

Saludos!
