### ISSUE TITLE
Base de Datos en Heroku

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC3103/2022-1-dudas#20]
Hay alguna forma de ver la base de datos que se creo en Heroku??

**Comment by dedarritchon** [comment]
Hola, claro, tienes que buscar las credenciales para conectarte aquí:

![image](https://user-images.githubusercontent.com/17625557/161160937-71cd3df5-ae72-4dd4-bd8a-f2f57d5334ae.png)

![image](https://user-images.githubusercontent.com/17625557/161161018-9e4a8b89-6598-4e63-b0e0-ad8280400c34.png)

![image](https://user-images.githubusercontent.com/17625557/161161108-079e53a7-2390-490d-bc65-594622b470fa.png)

Si se fijan bien Heroku usa Amazon Elastic Compute Cloud (Amazon EC2) como infraestructura para proveer este servicio, de hecho todo Heroku está construido sobre AWS 😱🤯

Usando esas credenciales podrás acceder a la base de datos desde cualquier cliente o visualizador de bases de datos.

Saludos!

**Comment by dedarritchon** [comment]
Cuando instalas el plugin, Heroku crea una variable de ambiente llamada `DATABASE_URL` donde vienen las credenciales en una sola línea (como la URI que sale en la foto de arriba), para que tu app pueda conectarse a la DB:

![image](https://user-images.githubusercontent.com/17625557/161162280-cf4b7f07-6ccd-4504-95be-a5cf3488d008.png)
