### ISSUE TITLE
Duda con tests en Conceder Autorización

### ISSUE THREAD

**Issue by dtmaltrain** [IIC3103/2022-1-dudas#21]
![image](https://user-images.githubusercontent.com/37244943/161170607-bf6d5a3f-1b0c-447f-8e3e-2e7953bc45a7.png)

Ese test espera una respuesta 403, que entiendo es cuando se tiene un token valido pero de otro usuario, pero yo estoy devolviendo 404 user not found, ya que ese usuario claramente no existe, ¿Qué debo hacer, cambio de orden el chequeo para esta request?

Además en la documentacion del la api, esta request no tiene ejemplo de response 403 
![image](https://user-images.githubusercontent.com/37244943/161170780-7385e6ba-7c32-455a-b7d7-d3afc5548ab9.png)

Gracias!

**Comment by dedarritchon** [comment]
Hola @dtmaltrain, Sí para todos los endpoints que requieran autenticación lo primero que deben chequear es el token y su validez, y en todos aplicar las mismas reglas de primero 401 Unauthorized y luego 403 Forbidden.
