### ISSUE TITLE
Ingreso a página con tokens

### ISSUE THREAD

**Issue by MatiasBarraF** [IIC3103/2022-1-dudas#22]
Cuando ustedes corran las pruebas, tenemos que asumir que tienen los tokens? o de que forma van a poder acceder a los diferentes user_tokens por ejemplo?

**Comment by dedarritchon** [comment]
Hola @MatiasBarraF! Cuando creemos un usuario, tu app nos debe retornar el user token, y ese vamos a usar para los siguientes requests (eso es lo que está haciendo actualmente el tester de la planilla). Recuerda que al crear un usuario tu app retorna:
```
{
    “id”: <user_id>
    “token”: <token>
}
```
Saludos!
