### ISSUE TITLE
Duda status code en endpoint /users/<user_id>/<scope>

### ISSUE THREAD

**Issue by vapina** [IIC3103/2022-1-dudas#23]
¡Hola!

Tengo una duda sobre el status code en el endpoint `/users/<user_id>/<scope>` cuando **el access token está vencido**. Este debería ser `401 Unauthorized` con body `{"error": "invalid token"}` o `403 Forbidden` con body `{"error": "you don't have access to this resource"}`

Muchas gracias.

**Comment by dedarritchon** [comment]
Hola! Cuando el token está vencido debe ser derechamente inválido (como si no existiera), es decir `401 Unauthorized`
