### ISSUE TITLE
Inconsistencias entre body response del enunciado y documentación de la API

### ISSUE THREAD

**Issue by vapina** [IIC3103/2022-1-dudas#24]
¡Hola!

Revisando la documentación encontré que en el _endpoint_ para editar usuarios `PATCH users/<id>` hay inconsistencias entre lo que dice el enunciado y la documentación. En el enunciado dice que para el status code `400 Bad request`, el _body_ es `{“error”: “invalid update”}`, mientras que en la documentación dice `{"error": "invalid attributes"}`. Para el status code `409 Conflict` tambiñen, el _body_ en el enunciado es `{“error”: “username is taken”}`, mientras que en la documentación dice `{"error": "user already exists"}`. ¿Cuál debería quedar en cada caso?

Aún no he podido probar mi proyecto en la planilla de correción, así que perdón si esto afecta en el resultado de los test.

Muchas gracias! 👍🏼😊

**Comment by Deleon20** [comment]
Hola! 

La planilla se focaliza mas en los status code que en los mensajes de error. Si ves en la planilla, cuando revisa errores dice que el expected body es  ` "expected_body": {"error": "your error message"}`
