### ISSUE TITLE
Body_received:NULL en Tester, pero en Postman obtengo un body en formato JSON

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC3103/2022-1-dudas#25]
Hola buenas, hice la pregunta por Canvas hace unos días, pero tampoco he obtenido respuesta. Realizo el test en Postman y me funciona correctamente el return del body en JSON, sin embargo, en el tester me aparece que mi received_body es NULL, llevo varias horas tratando de encontrar cual podría ser el problema y no logro solucionarlo. El resto de los test en actualizar datos del usuario y obtener datos del usuario tira OK.
¿Alguna sugerencia?

**Comment by Crespy98** [comment]
Hola @bgfeuereisen revisa si lo comentado en la issue #16. 
![image](https://user-images.githubusercontent.com/53805136/161386329-83153688-1ded-45ca-bc05-b0579ed93665.png)
También fíjate en los status que debes retornar.

**Comment by bgfeuereisen** [comment]
Me pasa que el status es el mismo
![image](https://user-images.githubusercontent.com/53834466/161386484-6b92b8ad-3165-47ac-b1c3-162c62feb4dc.png)
En la issue #16 mencionan:  El test lo único que hace es tratar de crear nuevamente los usuarios que se crearon inmediatamente antes.
No me queda muy clara la respuesta de la issue que mencionas.
gracias

**Comment by Crespy98** [comment]
El status code que debes devolver es un 409, ya que estas intentando crear el mismo usuario de antes con un body valido. El status code 400 es cuando un campo del body es invalido y este no es el caso.
