### ISSUE TITLE
 local variable 'response' referenced before assignment

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC3103/2022-1-dudas#26]
Hola buenas, en el tester me aparece solamente el error 
local variable 'response' referenced before assignment, para la función oauth/grant, sin embargo no tengo dicha variable creada en ninguna parte del código. Asimismo, con heroku logs tampoco logro encontrar el error, pues nunca hace un request GET a dicha ruta oauth/grant methods="GET"

**Comment by dedarritchon** [comment]
Hola @bgfeuereisen!, ese error en general es cuando el request a tu app termina en timeout y el response queda indefinido, voy a revisarlo, saludos!

**Comment by bgfeuereisen** [comment]
Había un error en el url que entregaba la función grant, ya lo resolví.
gracias
