### ISSUE TITLE
Parametro promotion

### ISSUE THREAD

**Issue by sbersanii** [IIC3103/2022-1-dudas#27]
Hola, el un test de crear usuario me tira error porque entrega todos los datos del usuario menos "promotion" y por lo tanto se marca como "error": "invalid attributes". Pero el excel me dice que tengo que crearlo. ¿ Si no me dan el promotion debo asumir que es false ?

adjunto resultado test:

{"username": "6ix9ine", "name": "Daniel Hernandez", "password": "kldjkqwihjd", "psu_score": 120, "age": 25, "university": "New York Research Institute", "gpa_score": 20.04, "job": "Rapper", "salary": 39830499.3, "hospital": "Manhattan Health", "operations": ["Brain replacement"], "medical_debt": 2387893.1}, "request_headers": null, "expected_status": 201, "expected_body": {"id": "some_id", "token": "some_token"}, "status_received": 400, "body_received": null, "exception": "incorrect response"}}]}

**Comment by Deleon20** [comment]
Hola! La respuesta a tu pregunta esta en la issue #6
