### ISSUE TITLE
Postman entrega 403 Test entrega 401 con el mismo link, token e id

### ISSUE THREAD

**Issue by bfigueroa1** [IIC3103/2022-1-dudas#30]
Hola, por alguna razón hay tres test que en Postman me entregan estatus y mensaje correcto (403) pero que en el test entrega 401. Pruebo exactamente la mis request que se muestra en el test y en Postman funciona perfecto.

**Comment by dedarritchon** [comment]
Hola @bfigueroa1 puedes dar más detalles? si puedes pega el log por acá, saludos!

**Comment by bfigueroa1** [comment]
![Screenshot (241)](https://user-images.githubusercontent.com/53798670/161577262-45c8fb71-a407-44cd-a4b5-74780d88b0f7.png)

**Comment by bfigueroa1** [comment]
Bearer Token con "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOjIsImlhdCI6MTY0OTA0NzgwNn0.yaRtpZ5puaz5KIk0mFuemKZfo59TfIVC7jqg9fU5pEI"

**Comment by dedarritchon** [comment]
@bfigueroa1 al usar **Bearer Token** Postman incluye el siguiente header:

![image](https://user-images.githubusercontent.com/17625557/161578027-9f323aaa-8332-4ad1-8ab0-6f0b41234092.png)


Nosotros en la tarea no usamos el prefijo "Bearer ", sino que como se muestra en el enunciado usamos directamente el token sin ningún prefijo

**Comment by dedarritchon** [comment]
Así es como lo manda el tester y esto es lo que está respondiendo tu API
![image](https://user-images.githubusercontent.com/17625557/161578571-8f558e33-90dd-4c03-8610-7bdbb98c93d9.png)
