### ISSUE TITLE
Errores test

### ISSUE THREAD

**Issue by camaruri** [IIC3103/2022-1-dudas#31]
Tengo una duda de los errores que arrojan los test.
En el tester, en crear usuarios, el error que me sale es `local variable 'response' referenced before assignment` pero después en flujo simple y flujo complejo me sale "create_user": "OK", "app_requests_auth": "OK", "user_grants_auth": "OK".
Ademas si pruebo crear un usuario desde Postman si funciona.
Gracias.

**Comment by dedarritchon** [comment]
Hola @camaruri, tu app se queda pegada al hacer el siguiente request:

POST https://tarea117642043.herokuapp.com/users,
con body: {"hola": "chao"}

Saludos!
