### ISSUE TITLE
[T2] Eventos Accepted y Dennied

### ISSUE THREAD

**Issue by vblopez** [IIC3103/2022-1-dudas#35]
Hola ! 
No me queda claro que debería ocurrir cuando llegan estos eventos. En especifico me pasa con accepted que luego de este mensaje siempre vendrá un evento lobby o question, que redijirá a esas vistas, por lo que no sé si ignorar el accepted o me falta algún paso/vista entremedio.

Gracias

**Comment by dedarritchon** [comment]
Hola! Los eventos accepted y denied son los que te puede responder el server al intentar unirte (la respuesta frente a tu evento tipo join). La única utilidad del evento accepted es que dentro viene el id de la trivia actual (en los demás eventos no viene hasta que se resetea la trivia). El evento denied es solo para los casos en los que el server rechazó la conexión, por ejemplo si el evento viene con mal formato, si el id es incorrecto, si alguien ya está usando el mismo username, si el server está lleno, etc, y en el evento viene la razón de por qué el server rechazó la conexión (solo para que sepas el por qué).
Saludos!

**Comment by vapina** [comment]
Hola, con respecto a esto mismo, que se debería mostrar cuando se rechaza la entrada al servidor? Se debería mostrar el mensaje o solo debería continuar mostrando la landing page?

**Comment by dedarritchon** [comment]
Hola! Basta con mostrar un mensaje de error en la misma vista, saludos!
