### ISSUE TITLE
[Tarea 2] Mostrar pregunta correcta

### ISSUE THREAD

**Issue by vapina** [IIC3103/2022-1-dudas#37]
¡Hola!

En el enunciado se menciona que se debe mostrar si la pregunta respondida en la trivia fue correcta o incorrecta. En el segundo caso, se debe mostrar cuál era la respuesta correcta.

Saludos.

**Comment by dedarritchon** [comment]
Hola! Noo no es necesario mostrar cual era la respuesta correcta, saludos!
