### ISSUE TITLE
Response Usuario ya existe

### ISSUE THREAD

**Issue by mpbosnic** [IIC3103/2022-1-dudas#4]
Hola! 

Al intentar crear un usuario que ya existe el response indicado por el enunciado es distinto al de la documentación de la api:

Enunciado: 409 Conflict, {“error”: “user already exists”}
Docs: 409 Conflict, {“error”: "username already taken"}

Cuál de los dos debemos usar?

Gracias!

**Comment by arturokunder** [comment]
@mpbosnic se corrigió la documentación, para que quede de igual forma que el enunciado.

**Comment by mpbosnic** [comment]
Gracias!

**Comment by dedarritchon** [comment]
Hola @mpbosnic! En los casos de errores el body de la respuesta es un mensaje puramente informativo que no se va a revisar, lo importante e es que venga con el status correcto.

Saludos!
