### ISSUE TITLE
[T2] Jugar Trivia

### ISSUE THREAD

**Issue by IvaniaArias** [IIC3103/2022-1-dudas#40]
Holaa! Para la tarea no pude lograr que mandara las respuestas, puedo jugar la trivia desde el link de otra persona? 🙏  (Aunque tenga su uuid pero mi nombre)
Así no perder los puntos de esta parte :(
Saludos

**Comment by dedarritchon** [comment]
Hola, nooo  lamentablemente es requisito jugar desde tu propio cliente, saludos!
