### ISSUE TITLE
[T3] error 403 al acceder a bucket

### ISSUE THREAD

**Issue by sbersanii** [IIC3103/2022-1-dudas#41]
Hola, 
siguiendo los pasos de la documentación de google para acceder a los datos del bucket me arroja el error _"403 GET https://storage.googleapis.com/storage/v1/b/2022-01-tarea-3?projection=noAcl&prettyPrint=false: acceso-bucket-alumnos-tarea-3@taller-integracion-310700.iam.gserviceaccount.com does not have storage.buckets.get access to the Google Cloud Storage bucket."_ . Luego de buscar los errores encontré esto: 
![image](https://user-images.githubusercontent.com/56396783/166086363-c3e8ca05-1d83-4696-bc1f-6dd27171936f.png)

Será que mi código está en un script normal y no en una API? o hay algún problema de acceso al bucket?
Saludos

**Comment by dedarritchon** [comment]
Hola @sbersanii, la cuenta tiene los permisos correctos y funciona, ya le hemos probado y podemos acceder al bucket sin problemas. Puedes enviar el código que estás ejecutando? saludos!

**Comment by sbersanii** [comment]
Gracias por la pronta respuesta. Adjunto el código que es todo de documentación.
![image](https://user-images.githubusercontent.com/56396783/166086738-82976188-47e8-43c3-b51c-9f1cd1edc001.png)

**Comment by sbersanii** [comment]
En la documentación hacen    
 # Make an authenticated API request
    buckets = list(storage_client.list_buckets())
    print(buckets)
pero con esto me tira el mismo error, por eso intenté con el nombre del bucket.

**Comment by dedarritchon** [comment]
@sbersanii creo que los métodos del cliente que estás usando requieren más permisos que los necesarios para la tarea, por ejemplo **list_buckets()** te muestra todos los buckets del proyecto, pero la cuenta solo tiene acceso de lectura a un solo bucket, por lo que no puede mostrarte los demás.

Puedes probar con esto?

```
blobs = storage_client.list_blobs(bucket_name)
for blob in blobs:
    print(blob.name)
```

Ese es un método de lecutra que solo opera sobre un bucket mostrandote sus contenidos (blobs).
Luego teniendo el blob puedes acceder al contenido de cada blob usando métodos como:

`blob.download_to_filename(destination_file_name)`

para descargarlo a un archivo local o

`string = blob.download_as_string()`

para cargarlo en memoria.

Me comentas si tienes algún problema al correr esos métodos.
Saludos!

**Comment by sbersanii** [comment]
Ahí si me permite acceder. 
Muchas Gracias !

**Comment by sofi-camino** [comment]
¿Hay alguna solución para esto en JavaScript? Estoy teniendo el mismo error  pero me tira algo como esto la consola...

![Error](https://user-images.githubusercontent.com/49731598/167684426-e5af9aec-3f33-4703-abc1-3d9a7ae57e87.png)

Busqué si había alguna función "blob" pero no la pillo. 
He probado con storage.getBuckets y storage.getBuckets('bucket_name')

**Comment by dedarritchon** [comment]
Hola @sofi-camino , puedes tratar con el siguiente código?

```
const {Storage} = require('@google-cloud/storage');

creds = {
    ...
}

const storage = new Storage({credentials: creds});
const bucket = storage.bucket('2022-01-tarea-3');

async function listFiles() {
    // Lists files in the bucket
    const [files] = await bucket.getFiles();

    console.log('Files:');
    files.forEach(file => {
      console.log(file.name);
    });
}

listFiles().catch(console.error);

```

Donde creds es la cuenta de servicio definida directamente en el código.
Al correr eso debería mostrarte los archivos del buckets, luego teniendo los nombres puedes descargar cada uno.

![image](https://user-images.githubusercontent.com/17625557/168186967-38123968-c710-44bc-a33c-4e923bc2375b.png)

Referencias:
Primera respuesta de: https://stackoverflow.com/questions/57483826/how-to-init-google-cloud-storage-nodejs-client-library-with-service-account-cred
Documentación oficial de Google para el cliente de Nodejs: https://googleapis.dev/nodejs/storage/latest/Bucket.html#getFiles

Saludos!
