### ISSUE TITLE
[T3] sin acceso a storage.bucket.list

### ISSUE THREAD

**Issue by bgfeuereisen** [IIC3103/2022-1-dudas#42]
Hola buenas,
Estoy siguiendo los pasos del enunciado y de la documentación de google para conectarme al bucket, sin embargo, no lo estoy logrando.
Adjunto foto del problema.
![image](https://user-images.githubusercontent.com/53834466/166793230-e8ad3fd9-4749-4b9b-af95-a4eb24bb5698.png)
Alguna sugerencia?
gracias

**Comment by dedarritchon** [comment]
Hola @bgfeuereisen, puedes revisar los ejemplos de la respuesta al issue #41 , saludos!
