### ISSUE TITLE
[T3] ¿El datalake de cada categoría puede cambiar?

### ISSUE THREAD

**Issue by CristobalUrzua** [IIC3103/2022-1-dudas#43]
Buenas,

Sabemos, por ejemplo, que los datos del aire están divididos por años. Los datos del turismo están divididos por año y mes.  ¿Esto siempre será así? ¿Es posible que en una modificación de los datos, se nos entregue que el aire esté dividido por años y por mes? ¿O que incluso los datos de la categoría turismo se nos entreguen divididos por años, mes y día?

Espero su respuesta,

**Comment by Deleon20** [comment]
La estructura del datalake como esta no deberia cambiar, ahora, los archivos dentro de este si pueden ser modificados, creados o eliminados.
