### ISSUE TITLE
[T3] Duda gráfico de torta

### ISSUE THREAD

**Issue by frvalenzuela** [IIC3103/2022-1-dudas#45]
¿En el grafico de torta debemos tomar el promedio entre los años 2010 y 2019?

**Comment by Crespy98** [comment]
Hola @frvalenzuela, como se menciona en el enunciado si hay que tomar el periodo entre los años 2010 y 2019. 
![image](https://user-images.githubusercontent.com/53805136/167761258-a7a712a0-aa44-41e3-b3dc-f31af3b5f63e.png)

**Comment by frvalenzuela** [comment]
¡ Hola @Crespy98 !

Pero mi duda va en si tenemos que tomar el promedio del recycling_rate entre los años 2010 a 2019, o quizás podría ser tomar la suma de los recycling_rate entre los años 2010 a 2019. Mi interrogante no va en el tiempo si no más bien como agrupar ese periodo.

Saludos!

**Comment by Crespy98** [comment]
Toma un promedio entre los años 2010 y 2019 para realizar el grafico
