### ISSUE TITLE
[T3] Modelo base de datos

### ISSUE THREAD

**Issue by sbersanii** [IIC3103/2022-1-dudas#47]
Hola, 
¿para modelar las bases de datos debe haber alguna relación entre las tablas ?
Yo lo estoy haciendo como muchas tablas independientes. Por ejemplo: Aire/2020/03 es una tabla y Aire/2020/04 es otra, pero no hay una relación entre ellas por pertenecer a "Aire", ¿ está bien?.
Ojalá se entienda mi duda.

Saludos

**Comment by Deleon20** [comment]
Hola! 

Suena bastante ineficiente en terminos de base de datos, trata de agrupar los datos mas para disminuir la cantidad de tablas.
Considera quizas añadir un atributo extra que te permita hacer esto ultimo
