### ISSUE TITLE
Recorrecciones T2

### ISSUE THREAD

**Issue by IvaniaArias** [IIC3103/2022-1-dudas#48]
Holaa!
Quería consultar dónde encuentro la rúbrica de la corrección de la T2, con el puntaje asignado a cada ítem.

**Comment by Deleon20** [comment]
Hola

Cuando vayas a la tarea 2 en canvas, si bajas un poco veras la rubrica 

![image](https://user-images.githubusercontent.com/48283979/168172258-a3a64a9a-8fc3-4f87-a8fd-44078f1b5e38.png)

**Comment by IvaniaArias** [comment]
Hola @Deleon20, sii vi eso.
Pero no sale los puntajes respectivos que obtuve en cada item, que es lo que busco.

**Comment by Deleon20** [comment]
Mmm en el buzon suele aparecer los detalles de la entrega donde puedes ver la rubrica

**Comment by dedarritchon** [comment]
Hola @IvaniaArias puedes tratar de ver la rúbrica de nuevo? no estaban públicos los resultados en Canvas pero ahora deberían verse, saludos!
