### ISSUE TITLE
[T3]Poblema deploy script python en heroku

### ISSUE THREAD

**Issue by sbersanii** [IIC3103/2022-1-dudas#49]
Hola, 
Mi script de python en heroku me dice que hay un error, y al ver los logs me dice algo de la librería psycopg2, como que falla una función interna. Busqué soluciónes y la que hay es bajar la versión de python a una 2.7 o 2.algo . Pero heroku no aguanta esas versiones. Entonces no se que hacer, buscaría otra plataforma para subirlo pero no se si va a tener el addon para que corra el script cada cierto tiempo.

adjunto errores en heroku.

saludos

![image](https://user-images.githubusercontent.com/56396783/168192186-9bbd33b0-c7c9-4878-a1a3-14707bd15dd4.png)

**Comment by dedarritchon** [comment]
Hola @sbersanii , qué versión de **psycopg2** estás usando? al parecer estás usando una versión antigua que espera que la corras con python 2.7, y el tipo **basestring** no existe en Python 3+.

**Comment by sbersanii** [comment]
Hola, estoy usando la version 2.7.4 de psycopg2

**Comment by dedarritchon** [comment]
@sbersanii la version 2.7.4 de psycopg2 es de inicios del 2018, prueba subiendo a la [última versión](https://pypi.org/project/psycopg2/) 2.9.3 que sacaron a finales del 2021 y seguramente habrán arreglado ese bug.

Saludos!

**Comment by sbersanii** [comment]
Actualice la versión y funcionó! 
Gracias por tu respuesta
