### ISSUE TITLE
[Proyecto] Consulta de stock

### ISSUE THREAD

**Issue by dpacevedo** [IIC3103/2022-1-dudas#55]
Hola! Tengo una duda respecto a la consulta de stock, se mencionó que debemos mostrar todos los skus incluso los que tienen stock igual a 0. Considerando que el método **obtener skus con stock** retorna solo los skus con stock disponible, podemos asumir que los skus restantes, es decir, que no están en las listas de cada almacén pero si en el excel que nos entregaron, tienen stock igual a 0?

Gracias de antemano! 🌻

**Comment by dedarritchon** [comment]
Hola! si pueden asumir que los que no entrega el método **obtener skus con stock** tienen stock igual a 0, saludos!
