### ISSUE TITLE
Duda atributos requeridos para generar usuario

### ISSUE THREAD

**Issue by AlexGV7** [IIC3103/2022-1-dudas#6]
¿En el método POST /users qué atributos (ej. username, name, password, etc) sí o sí debe tener el json que es enviado a la API?

**Comment by dedarritchon** [comment]
Hola Alex,

Como se menciona en el enunciado, los únicos atributos requeridos para crear un usuario son:
- username: str
- name: str
- age: int
- password: str

Los demás atributos pueden ser nulos,
Saludos!
