### ISSUE TITLE
id tablas base de datos

### ISSUE THREAD

**Issue by sbersanii** [IIC3103/2022-1-dudas#7]
Hola, en el modelo sugerido para la base de datos de la tarea ponen que el type de los id (todas las tablas) es varchar. ¿Hay que hacerlo así o se puede poner como un int?¿ cual sería el propósito de que sea varchar en vez de int?

**Comment by dedarritchon** [comment]
Hola!

Puedes hacerlo como te sea más cómodo.

Una ventaja de que el id sea un string (no para la tarea en específico sino de forma general) es que te da más flexibilidad, por ejemplo puedes tener ids en formato **uuid**: "560a8451-a29c-41d4-a716-544676554400" o en formato **ObjectId** de Mongo: "5ae15168d4a5b37a08d14bed", en vez de estar restringido solo a números.

Saludos!

**Comment by dasolari** [comment]
Hola! En relación a este tema; definí mis modelos con _ids_ del tipo __uuid__ , pero hay veces que el request GET /users/:id falla debido a que algunas de las pruebas se realizan pasándole un número como id, las cuales además esperan una respuesta válida. ¿Es posible que se hayan hecho tests donde se _hardcodea_ el id?

**Comment by dedarritchon** [comment]
Hola @dasolari ! Acabo de corregir un bug que podría haber provocado eso, me puedes avisar si vuelve a ocurrir? si pasa de nuevo copia el log por acá por favor.
saludos!

**Comment by dasolari** [comment]
Ya no volvió a pasar. Gracias!
