### ISSUE TITLE
Diferencia Status Code /oauth/request entre documentación y enunciado

### ISSUE THREAD

**Issue by juanfcolopez** [IIC3103/2022-1-dudas#8]
Hola,

Una consulta, revisando el _status code_ al realizar el GET al _endpoint_ /oauth/request, en el enunciado se específica que si todo está correcto debe responder con un 202 _Accepted_, en cambio en la documentación, en este mismo escenario, responde con un 200 OK. 

¿El esperado es el del enunciado o el de la documentación?

**Comment by dedarritchon** [comment]
Hola @juanfcolopez, gracias por avisar! Dado que es un detalle muy chico se van a considerar ambos correctos. Saludos!
